version: "3.8"

services:
  aws-monitor:
    build: .
    container_name: aws-cost-monitor
    ports:
      - "8501:8501"
    environment:
      # AWS credentials (for local development only)
      # In production, use IAM roles
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - AWS_REGION=${AWS_REGION:-us-east-1}

      # Application settings
      - COST_ANOMALY_THRESHOLD=${COST_ANOMALY_THRESHOLD:-20}
      - DATA_REFRESH_INTERVAL=${DATA_REFRESH_INTERVAL:-300}

    volumes:
      # Mount AWS credentials for local development
      # Remove this in production
      - ~/.aws:/home/appuser/.aws:ro

      # Mount application code for development
      - ./aws_monitor:/app/aws_monitor:ro

    restart: unless-stopped

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: aws-monitor-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - aws-monitor
  #   restart: unless-stopped

# Optional: Add networks for multi-container setup
networks:
  default:
    name: aws-monitor-network
